# Generated by Django 2.1.5 on 2019-09-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vehicle_no', models.CharField(max_length=100, unique=True)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=1000)),
            ],
        ),
    ]
