# Generated by Django 2.1.5 on 2019-09-15 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fac',
            name='in_out',
            field=models.CharField(default='Entry', max_length=255),
        ),
        migrations.AddField(
            model_name='fac',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 9, 8, 45, 448208)),
        ),
    ]
