# Generated by Django 2.1.5 on 2019-09-15 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20190915_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fac',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 9, 9, 1, 571817)),
        ),
    ]
