# Generated by Django 2.1.5 on 2019-09-15 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20190915_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fac',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 9, 15, 4, 229548)),
        ),
    ]
