# Generated by Django 2.1.5 on 2019-09-15 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20190915_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fac',
            name='time_in',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 9, 27, 51, 760747)),
        ),
        migrations.AlterField(
            model_name='fac',
            name='vehicle_no',
            field=models.CharField(max_length=100),
        ),
    ]
