# Generated by Django 2.1.5 on 2019-09-15 08:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0018_auto_20190915_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fac',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 14, 7, 19, 79878)),
        ),
    ]
