# Generated by Django 2.1.5 on 2019-09-15 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('vehicle_no', models.CharField(max_length=10, unique=True)),
                ('vehicle_type', models.CharField(max_length=10, unique=True)),
                ('purpose', models.CharField(max_length=1000, unique=True)),
            ],
        ),
    ]
