# Generated by Django 2.1.5 on 2019-09-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20190915_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='purpose',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='guest',
            name='vehicle_type',
            field=models.CharField(max_length=10),
        ),
    ]
